//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchGeometry
    {
        public int Id { get; set; }
        public Nullable<int> CompanyBranchDetailId { get; set; }
        public string Geometry { get; set; }
    
        public virtual CompanyBranchDetail CompanyBranchDetail { get; set; }
    }
}
