//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPromotion
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string PromotionText { get; set; }
        public int AreaCode { get; set; }
        public Nullable<bool> IsAreaCodeWildCard { get; set; }
        public Nullable<System.DateTime> PromotionExpiryDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
    }
}
