//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBranchDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyBranchDetail()
        {
            this.CompanyUserDetails = new HashSet<CompanyUserDetail>();
            this.BranchGeometries = new HashSet<BranchGeometry>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Description { get; set; }
        public string FirstLineOfAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int AreaCode { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyUserDetail> CompanyUserDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchGeometry> BranchGeometries { get; set; }
    }
}
