//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyUserDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsBranchWildCard { get; set; }
        public Nullable<int> CompanyBranchId { get; set; }
    
        public virtual CompanyBranchDetail CompanyBranchDetail { get; set; }
        public virtual CompanyProfile CompanyProfile { get; set; }
        public virtual User User { get; set; }
    }
}
