//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountActivation
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string VerificationText { get; set; }
        public Nullable<System.DateTime> VerificationTextDateTime { get; set; }
        public Nullable<int> VerificationTextExpiryInSeconds { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
