//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MunicipalityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipalityAnnouncement
    {
        public int Id { get; set; }
        public int MunicipalityId { get; set; }
        public string AnnouncementText { get; set; }
        public bool IsAreaWildCard { get; set; }
        public int AreaCode { get; set; }
        public Nullable<System.DateTime> AnnouncementExpiryDate { get; set; }
        public int IsActiveAnnouncement { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Municipality Municipality { get; set; }
    }
}
