//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MunicipalityAccess.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MunicipalityDevEnvEntities : DbContext
    {
        public MunicipalityDevEnvEntities()
            : base("name=MunicipalityDevEnvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenity> Amenities { get; set; }
        public virtual DbSet<AmenityArea> AmenityAreas { get; set; }
        public virtual DbSet<Municipality> Municipalities { get; set; }
        public virtual DbSet<MunicipalityAmenity> MunicipalityAmenities { get; set; }
        public virtual DbSet<MunicipalityAnnouncement> MunicipalityAnnouncements { get; set; }
        public virtual DbSet<MunicipalityAreaCode> MunicipalityAreaCodes { get; set; }
        public virtual DbSet<MunicipalityUser> MunicipalityUsers { get; set; }
        public virtual DbSet<MunicipalityUserType> MunicipalityUserTypes { get; set; }
        public virtual DbSet<MunicipalityUserVerfication> MunicipalityUserVerfications { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
    }
}
