//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MunicipalityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipalityUserVerfication
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int VerificationText { get; set; }
        public System.DateTime VerificationTextDateTime { get; set; }
        public System.DateTime VerificationTextExpiryInSeconds { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual MunicipalityUser MunicipalityUser { get; set; }
    }
}
