//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MunicipalityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipalityUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MunicipalityUser()
        {
            this.MunicipalityUserVerfications = new HashSet<MunicipalityUserVerfication>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int MunicipalityId { get; set; }
        public int MunicipalityUserTypeId { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
    
        public virtual Municipality Municipality { get; set; }
        public virtual MunicipalityUserType MunicipalityUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MunicipalityUserVerfication> MunicipalityUserVerfications { get; set; }
    }
}
