//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MunicipalityAccess.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipalityAreaCode
    {
        public int Id { get; set; }
        public int MunicipalityId { get; set; }
        public Nullable<int> AreaCode { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
    
        public virtual Municipality Municipality { get; set; }
    }
}
